### ISSUE TITLE
Uncertainty-aware Dynamic Smooth Refinement

### ISSUE THREAD

**Issue by haibinswe** [lemoshu/AC-MT#1]
How to apply the work into Uncertainty-aware Dynamic Smooth Refinement for noisy labels? i.e., your MTCL work.

**Comment by lemoshu** [comment]
Thanks for your interest.

You can directly adapt the ambiguity-selective consistency loss into the consistency loss in MTCL. But I haven't tried this, you may need to further tune the tradeoff weight between the LQ loss and the consistency loss.
